repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
  - repo: local
    hooks:
      - id: add-area-scope
        name: add area scope to commit message
        entry: scripts/commit-scope.sh
        language: system
        stages: [prepare-commit-msg]
