import { test, expect } from '../helpers/e2e.js'
import { type Page } from '@playwright/test'
import { grantDevicePermission, mockIdFor, type DeviceFilter } from '../helpers/e2e-devices.js'
import {
  sendInput,
  waitForOutputReport,
  startWebhidMock,
  type WebhidMockProcess
} from '../helpers/e2e-process.js'

// Multi-device harness: each generated descriptor is its own mock device with
// its own VID/PID (see DEVICES in ../helpers/e2e-devices.ts). The serial chain
// targets the **vendor** device for the primary input/output/feature path and
// the **gamepad** device (un-numbered 5-byte input) for the WS-data-plane and
// fresh-pairing gates. Each test names its device via a fixture and selects it
// by VID/PID, never by array index, because more than one device can be paired
// at once (vendor + gamepad after the mid-chain gamepad gate).
const VENDOR = mockIdFor('vendor')
const GAMEPAD = mockIdFor('gamepad')

// Vendor descriptor: report ID 1, 64-byte input + 64-byte output. Sizes derived
// from the generated bytes (report_size*count).
const VENDOR_INPUT_SIZE = 64
const VENDOR_OUTPUT_ID = 1
const FEATURE_REPORT_ID = 0x02
// Gamepad descriptor: no report ID, 40 bits = 5-byte input.
const GAMEPAD_INPUT_SIZE = 5

// Values serialized into every page.evaluate that touches the vendor device.
// The evaluate callback runs inside the page, where module-scope constants are
// unreachable, so the filter + sizes are passed in as the arg instead of being
// hardcoded in page code.
const VENDOR_CTX = {
  f: VENDOR,
  size: VENDOR_INPUT_SIZE,
  outputId: VENDOR_OUTPUT_ID,
  featureId: FEATURE_REPORT_ID
}

type VendorCtx = typeof VENDOR_CTX

interface ReportEvent {
  reportId: number
  data: number[]
}

// Registers an oninputreport listener on the device selected by VID/PID and
// resolves with the next report it receives. The page.evaluate blocks the
// page's command queue until the report arrives, so the trigger must come from
// outside Playwright (the mock's stdin), never a second evaluate.
//
// `sentinel` optionally waits for a report whose data[marker.index] equals
// marker.value, skipping earlier/spurious reports (e.g. a stale report from a
// prior test still in flight on the WS data plane). Functions cannot be
// serialized through page.evaluate, so the marker is a plain value/index,
// which each value-asserting test makes unique to its own payload.
function sleep(ms: number): Promise<void> {
  const { promise, resolve } = Promise.withResolvers<void>()
  setTimeout(resolve, ms)
  return promise
}

// Races p against a timer that rejects, so a report/event that never arrives
// surfaces as an error instead of hanging the test forever.
function withTimeout<T>(p: Promise<T>, ms: number, msg: string): Promise<T> {
  const { promise, reject } = Promise.withResolvers<never>()
  const t = setTimeout(() => reject(new Error(msg)), ms)
  return Promise.race([p, promise]).finally(() => clearTimeout(t))
}

// Sends the report and returns the matching event, retrying the send if the
// WS data plane drops the first report under load (seen when both e2e
// projects run concurrently). Keep `payload` identical across retries so the
// marker predicate always accepts whichever attempt's report arrives.
async function sendUntilReported(
  device: WebhidMockProcess,
  page: Page,
  flt: DeviceFilter,
  reportId: number,
  payload: number[],
  marker: { index: number; value: number }
): Promise<ReportEvent> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const reportPromise = nextInputReport(page, flt, marker)
    await sleep(250)
    sendInput(device, reportId, payload)
    try {
      return await withTimeout(reportPromise, 2000, 'report not received on attempt ' + attempt)
    } catch (err) {
      if (attempt === 4) throw err
    }
  }
  throw new Error('unreachable')
}

function nextInputReport(
  page: Page,
  flt: DeviceFilter,
  marker?: { index: number; value: number }
): Promise<ReportEvent> {
  return page.evaluate(
    ({ f, link }: { f: DeviceFilter; link: { index: number; value: number } | undefined }) => {
      const { promise, resolve, reject } = Promise.withResolvers<ReportEvent>()
      void navigator.hid.getDevices().then((ds) => {
        const d = ds.find((x) => x.vendorId === f.vendorId && x.productId === f.productId)
        if (!d) {
          reject(new Error(`device not paired: ${JSON.stringify(f)}`))
          return
        }
        d.oninputreport = (event) => {
          const r: ReportEvent = {
            reportId: event.reportId,
            data: Array.from(new Uint8Array(event.data.buffer))
          }
          if (!link || r.data[link.index] === link.value) resolve(r)
        }
      })
      return promise
    },
    { f: flt, link: marker }
  )
}

// Single serial chain over a worker-scoped page (see tests/helpers/e2e.ts):
// the vendor device is paired once (test 2) and opened once (test 6), then
// reused by every report test that follows; the gamepad device is paired once
// at the WS-data-plane gate (test 15). No per-test reset. Close tests run after
// all device-using tests; forget (which unpairs) is last because it destroys
// the state every later test depends on. Hot-plug (test 16) drops the vendor
// device from the page's registry on disconnect, so tests after it start from
// a freshly-closed recreated device.
test.describe.serial('WebHID E2E', () => {
  test('navigator.hid is polyfilled', async ({ sharedPage }) => {
    expect(await sharedPage.evaluate(() => typeof navigator.hid !== 'undefined')).toBe(true)
  })

  test('grant vendor permission and verify VID/PID, collections', async ({
    sharedPage,
    vendorDevice
  }) => {
    const count = await grantDevicePermission(sharedPage, [VENDOR])
    expect(count).toBe(1)
    const info = await sharedPage.evaluate(
      async (f: DeviceFilter) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === f.vendorId && x.productId === f.productId)!
        return {
          vendorId: d.vendorId,
          productId: d.productId,
          collectionCount: d.collections.length
        }
      },
      VENDOR
    )
    expect(info.vendorId).toBe(vendorDevice.vid)
    expect(info.productId).toBe(vendorDevice.pid)
    // vendor.bin carries two application collections (a 3-byte joystick
    // collection plus the 64-byte vendor report-ID-1 collection).
    expect(info.collectionCount).toBe(2)
  })

  // Paired but not yet open: the polyfill rejects with InvalidStateError
  // ('Device is not open') for every report API.
  test('sendReport fails before open', async ({ sharedPage }) => {
    const errorName = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        try {
          await d.sendReport(ctx.outputId, new Uint8Array(ctx.size))
          return null
        } catch (e) {
          return e instanceof Error ? e.name : String(e)
        }
      },
      VENDOR_CTX
    )
    expect(errorName).toBe('InvalidStateError')
  })

  test('sendFeatureReport fails before open', async ({ sharedPage }) => {
    const errorName = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        try {
          await d.sendFeatureReport(ctx.featureId, new Uint8Array(4))
          return null
        } catch (e) {
          return e instanceof Error ? e.name : String(e)
        }
      },
      VENDOR_CTX
    )
    expect(errorName).toBe('InvalidStateError')
  })

  test('receiveFeatureReport fails before open', async ({ sharedPage }) => {
    const errorName = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        try {
          await d.receiveFeatureReport(ctx.featureId)
          return null
        } catch (e) {
          return e instanceof Error ? e.name : String(e)
        }
      },
      VENDOR_CTX
    )
    expect(errorName).toBe('InvalidStateError')
  })

  // Open once; every test from here to the close tests reuses this open
  // device (open() on an open device throws, so none of them call it again).
  test('open device', async ({ sharedPage }) => {
    const opened = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        await d.open()
        return d.opened
      },
      VENDOR_CTX
    )
    expect(opened).toBe(true)
  })

  test('receive 64-byte input packet', async ({ sharedPage, vendorDevice }) => {
    const reportPromise = nextInputReport(sharedPage, VENDOR)
    await sleep(200)
    sendInput(vendorDevice, 1, new Array<number>(VENDOR_INPUT_SIZE).fill(0))
    const event = await reportPromise
    expect(event.reportId).toBe(1)
    expect(event.data.length).toBe(VENDOR_INPUT_SIZE)
  })

  test('receive input packet with button press', async ({ sharedPage, vendorDevice }) => {
    // Payload: byte 0 = buttons; byte 1 = unique marker this test waits for.
    // Retried via sendUntilReported because the WS data plane can drop the
    // first report when both e2e projects run concurrently.
    const packet = new Array<number>(VENDOR_INPUT_SIZE).fill(0)
    packet[0] = 0xff
    packet[1] = 0xe1
    const event = await sendUntilReported(vendorDevice, sharedPage, VENDOR, 1, packet, {
      index: 1,
      value: 0xe1
    })
    expect(event.reportId).toBe(1)
    expect(event.data.length).toBe(VENDOR_INPUT_SIZE)
    expect(event.data[0]).toBe(0xff)
  })

  test('multiple input reports in sequence', async ({ sharedPage, vendorDevice }) => {
    for (let i = 0; i < 3; i++) {
      // A per-iteration marker in byte 1 (0xa0+i) means a report lingered from
      // an earlier iteration can't satisfy this one's wait.
      const reportPromise = nextInputReport(sharedPage, VENDOR, { index: 1, value: 0xa0 + i })
      await sleep(500)
      const packet = new Array<number>(VENDOR_INPUT_SIZE).fill(0)
      packet[0] = i
      packet[1] = 0xa0 + i
      sendInput(vendorDevice, 1, packet)
      const event = await reportPromise
      expect(event.reportId).toBe(1)
      expect(event.data[0]).toBe(i)
      expect(event.data[1]).toBe(0xa0 + i)
    }
  })

  test('addEventListener inputreport fires alongside oninputreport', async ({
    sharedPage,
    vendorDevice
  }) => {
    // Register BOTH listeners in a single page.evaluate call. Two separate
    // page.evaluate calls would deadlock: the first returns a Promise that
    // blocks the page's command queue until an input report arrives,
    // preventing the second from ever executing.
    const dualPromise = sharedPage.evaluate((f: DeviceFilter) => {
      const { promise, resolve, reject } = Promise.withResolvers<{
        onInput: ReportEvent
        addEventListener: ReportEvent
      }>()
      void navigator.hid.getDevices().then((ds) => {
        const d = ds.find((x) => x.vendorId === f.vendorId && x.productId === f.productId)
        if (!d) {
          reject(new Error(`device not paired: ${JSON.stringify(f)}`))
          return
        }
        const toResult = (event: HIDInputReportEvent): ReportEvent => ({
          reportId: event.reportId,
          data: Array.from(new Uint8Array(event.data.buffer))
        })
        let onInput: ReportEvent | null = null
        let onAdd: ReportEvent | null = null
        d.oninputreport = (event) => {
          onInput = toResult(event)
          if (onAdd) resolve({ onInput, addEventListener: onAdd })
        }
        d.addEventListener('inputreport', (event) => {
          onAdd = toResult(event)
          if (onInput) resolve({ onInput, addEventListener: onAdd })
        })
      })
      return promise
    }, VENDOR)

    // Wait for the WS data plane to connect. spawnDataPlane is called
    // without await in the bridge's open handler, so open() returns
    // before the worker's WebSocket is established.
    await sleep(500)

    sendInput(vendorDevice, 1, new Array<number>(VENDOR_INPUT_SIZE).fill(0))

    const { onInput, addEventListener: addEvt } = await dualPromise
    expect(onInput.reportId).toBe(1)
    expect(addEvt.reportId).toBe(1)
    expect(onInput.data.length).toBe(addEvt.data.length)
  })

  test('inputreport.data does not include report-ID byte for vendor report', async ({
    sharedPage,
    vendorDevice
  }) => {
    // Payload with a distinctive leading byte (0xaa, distinct from the report
    // ID 1) that also serves as the wait marker: if the polyfill leaked the ID
    // into .data we'd see 0x01 at position 0, not 0xaa.
    const reportPromise = nextInputReport(sharedPage, VENDOR, { index: 0, value: 0xaa })
    await sleep(500)
    const packet = new Array<number>(VENDOR_INPUT_SIZE).fill(0)
    packet[0] = 0xaa
    sendInput(vendorDevice, 1, packet)
    const event = await reportPromise
    expect(event.reportId).toBe(1)
    expect(event.data.length).toBe(VENDOR_INPUT_SIZE)
    expect(event.data[0]).toBe(0xaa)
  })

  test('sendReport succeeds with output report ID after open', async ({
    sharedPage,
    vendorDevice
  }) => {
    // Vendor descriptor defines an output report with ID 1 (64 bytes).
    const outputPromise = waitForOutputReport(vendorDevice)
    await sleep(200)
    await sharedPage.evaluate(async (ctx: VendorCtx) => {
      const ds = await navigator.hid.getDevices()
      const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
      await d.sendReport(ctx.outputId, new Uint8Array(ctx.size).fill(0x42))
    }, VENDOR_CTX)
    const output = await outputPromise
    // The daemon prepends the report ID (1) to the payload when writing.
    expect(output.data[0]).toBe(VENDOR_OUTPUT_ID)
  })

  test('sendFeatureReport succeeds after open', async ({ sharedPage }) => {
    await sharedPage.evaluate(async (ctx: VendorCtx) => {
      const ds = await navigator.hid.getDevices()
      const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
      await d.sendFeatureReport(ctx.featureId, new Uint8Array([0xab, 0xab, 0xab, 0xab]))
    }, VENDOR_CTX)
  })

  test('receiveFeatureReport from vendor returns data', async ({ sharedPage }) => {
    const data = await sharedPage.evaluate(async (ctx: VendorCtx) => {
      const ds = await navigator.hid.getDevices()
      const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
      const view = await d.receiveFeatureReport(ctx.featureId)
      return Array.from(new Uint8Array(view.buffer))
    }, VENDOR_CTX)
    expect(Array.isArray(data)).toBe(true)
  })

  // Fresh pairing gate: grant the gamepad device's permission, then drive its
  // unnumbered 5-byte input through the WS data plane on a page with a URL
  // fragment. Tests after this run with BOTH devices paired, which is why
  // every device access is by VID/PID rather than array index.
  test('WS data plane works with gamepad when the page URL has a fragment', async ({
    sharedPage,
    gamepadDevice
  }) => {
    const count = await grantDevicePermission(sharedPage, [GAMEPAD])
    expect(count).toBe(1)

    const url = sharedPage.url()
    await sharedPage.goto(url + '#frag', { waitUntil: 'domcontentloaded', timeout: 15000 })

    // The grant survives the navigation (origin-level allow persists), but the
    // freshly paired gamepad is not open yet, and input reports only flow to
    // an open device. Open it in the post-fragment document, then drive its
    // unnumbered 5-byte input through the WS data plane.
    await sharedPage.evaluate(async (f: DeviceFilter) => {
      const ds = await navigator.hid.getDevices()
      const d = ds.find((x) => x.vendorId === f.vendorId && x.productId === f.productId)!
      await d.open()
    }, GAMEPAD)

    const reportPromise = nextInputReport(sharedPage, GAMEPAD)
    await sleep(200)
    sendInput(gamepadDevice, 0, new Array<number>(GAMEPAD_INPUT_SIZE).fill(0))
    const event = await reportPromise
    expect(event.reportId).toBe(0)
    expect(event.data.length).toBe(GAMEPAD_INPUT_SIZE)
  })

  // Destroys and recreates the vendor uhid device. The browser-side grant
  // survives the disconnect, but the page drops the device from its registry,
  // so the tests below start from a freshly-closed recreated device.
  test('device disconnect event fires when vendor mock is destroyed', async ({
    sharedPage,
    vendorDevice
  }) => {
    const disconnected = sharedPage.evaluate(() => {
      const { promise, resolve, reject } = Promise.withResolvers<boolean>()
      navigator.hid.addEventListener('disconnect', () => resolve(true))
      setTimeout(() => reject(new Error('disconnect event not received within 10s')), 10000)
      return promise
    })
    vendorDevice.process.stdin!.write('{"cmd":"destroy"}\n')
    expect(await disconnected).toBe(true)

    // The vendor mock is worker-scoped and shared with later tests, so recreate
    // the device after destroying it, hand the new process back to the fixture.
    const m = startWebhidMock('vendor.bin', vendorDevice.vid, vendorDevice.pid)
    await m.ready
    vendorDevice.process = m.process
    vendorDevice.ready = m.ready

    // Wait for the daemon to re-enumerate the recreated vendor device before
    // the close tests rely on getDevices() finding it.
    await sharedPage.evaluate((f: DeviceFilter) => {
      const start = Date.now()
      return (async () => {
        for (;;) {
          const ds = await navigator.hid.getDevices()
          if (ds.some((x) => x.vendorId === f.vendorId && x.productId === f.productId)) return
          if (Date.now() - start > 10000) {
            throw new Error('vendor device did not re-enumerate after mock recreate')
          }
          const { promise: t, resolve: done } = Promise.withResolvers<void>()
          setTimeout(done, 100)
          await t
        }
      })()
    }, VENDOR)
  })

  test('open and close device', async ({ sharedPage }) => {
    const result = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        await d.open()
        const wasOpen = d.opened
        await d.close()
        return { wasOpen, nowOpen: d.opened }
      },
      VENDOR_CTX
    )
    expect(result.wasOpen).toBe(true)
    expect(result.nowOpen).toBe(false)
  })

  test('open and close multiple times', async ({ sharedPage }) => {
    await sharedPage.evaluate(async (ctx: VendorCtx) => {
      const ds = await navigator.hid.getDevices()
      const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
      for (let i = 0; i < 3; i++) {
        await d.open()
        await d.close()
      }
    }, VENDOR_CTX)
  })

  // Forget unpairs the device; it is the terminal state of the chain, so the
  // whole assertion lives in one evaluate (there is no device to fetch after).
  test('forget unpairs the device and sendReport fails after', async ({ sharedPage }) => {
    const result = await sharedPage.evaluate(
      async (ctx: VendorCtx) => {
        const ds = await navigator.hid.getDevices()
        const d = ds.find((x) => x.vendorId === ctx.f.vendorId && x.productId === ctx.f.productId)!
        await d.open()
        await d.forget()
        let sendError: string | null = null
        try {
          await d.sendReport(ctx.outputId, new Uint8Array(ctx.size))
        } catch (e) {
          sendError = e instanceof Error ? e.name : String(e)
        }
        return { sendError, remaining: (await navigator.hid.getDevices()).length }
      },
      VENDOR_CTX
    )
    expect(result.sendError).toBe('InvalidStateError')
    // vendor is forgotten; the previously-paired gamepad device remains.
    expect(result.remaining).toBe(1)
  })
})