name: Build Addon

on:
  push:
    branches: [ main ]
    paths:
      - 'addon/**'
      - '.github/workflows/build-addon.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'addon/**'
      - '.github/workflows/build-addon.yml'
  workflow_dispatch:

jobs:
  build-addon:
    name: Build Addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Define variables
        id: variables
        shell: bash
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          echo "VERSION=$(git describe --tags | sed 's/^v//;s/_/./;s/\([^-]*-g\)/r\1/;s/-/./g')" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: npm ci

      - name: Lint addon
        run: npm run lint

      - name: Build Addon XPI
        run: |
          make build-addon
          mv dist/webhid-addon.xpi dist/webhid-addon-${{ steps.variables.outputs.VERSION }}.xpi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist/webhid-addon-${{ steps.variables.outputs.VERSION }}.xpi
          archive: false
